image: andreroquem/clang-build

pipelines:
  default:
    - step:
        script:
          - mkdir build
          - cd build
          - cmake .. -DBUILD_TEST=1
          - make
          - make check